name: My Test Single Project
on:
  push:
  pull_request:
jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
     - name: Check out code into the Go module directory
       uses: actions/checkout@v4
     - name: Security Scan
       uses: securego/gosec@master
       with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
         args: '-no-fail -fmt sonarqube -out gosec_sonar_report.json ./...'
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
